---
title: "Untitled"
output: html_document
---

```{r}
LR_model=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/LR_linear_regression_for_each_gene/top9_Abs_copy_comp_LR_model.rds")
copy_number=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_itsel_across_expression_copy_mut.rds")
co_exp_ess=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_abs_top10_Co_Exp_Ess_across_expression.rds")
dim(copy_number)
essentiality=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Crispr_across_cell_Line_normalized.rds")
co_exp_ess=co_exp_ess[,1:11]
co_exp_ess$copy_number=copy_number[,4]
co_exp_ess$essentiality=as.vector(essentiality)
names(LR_model)=as.vector(unique(co_exp_ess[,2]))

setwd("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/LR_linear_regression_for_each_gene")
#train_model_pre<-NULL
train_model_pre<-NULL
train_model_pre_cor<<-NULL

one_gene_model<-function(gene){
  index=which(co_exp_ess[,2] == gene)
  data=co_exp_ess[index[1:385],3:13]
  model_index=match(gene,names(LR_model))

  y_pre=predict(LR_model[[model_index]],data)
  train_model_pre<<-cbind(train_model_pre,y_pre)
  train_model_pre_cor<<-rbind(train_model_pre_cor,c(gene,unlist(cor.test(y_pre,co_exp_ess[index[1:385],13]))[c(3,4)]))
  
  }
result=apply(matrix(as.vector(unique(co_exp_ess[,2]))),1,one_gene_model)

saveRDS(train_model_pre,file="top9_Abs_copy_comp_LR_model_train_predict.rds")
saveRDS(train_model_pre_cor,file="top9_Abs_copy_comp_LR_model_train_predict_cor.rds")
```



```{r}

copy_number=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_itsel_across_expression_copy_mut.rds")
co_exp_ess=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_abs_top10_Co_Exp_Ess_across_expression.rds")
dim(copy_number)
essentiality=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Crispr_across_cell_Line_normalized.rds")
co_exp_ess=co_exp_ess[,1:11]
co_exp_ess$copy_number=copy_number[,4]
co_exp_ess$essentiality=as.vector(essentiality)

library(ridge)
setwd("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/Ridge_regression_for_each_gene")
Ridge_model=readRDS("top9_Abs_copy_comp_RR_model.rds")
names(Ridge_model)=as.vector(unique(co_exp_ess[,2]))
#train_model_pre<-NULL
train_model_pre<-NULL
train_model_pre_cor<<-NULL
one_gene_model<-function(gene){
  index=which(co_exp_ess[,2] == gene)
  data=co_exp_ess[index[1:385],3:13]
  model_index=match(gene,names(Ridge_model))

  y_pre=predict(Ridge_model[[model_index]],data)
  train_model_pre<<-cbind(train_model_pre,y_pre)
  train_model_pre_cor<<-rbind(train_model_pre_cor,c(gene,unlist(cor.test(y_pre,co_exp_ess[index[1:385],13]))[c(3,4)]))
  
  }
result=apply(matrix(as.vector(unique(co_exp_ess[,2]))),1,one_gene_model)

saveRDS(train_model_pre,file="top9_Abs_copy_comp_Ridge_model_train_predict.rds")
saveRDS(train_model_pre_cor,file="top9_Abs_copy_comp_Ridge_model_train_predict_cor.rds")
```




```{r}
copy_number=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_itsel_across_expression_copy_mut.rds")
co_exp_ess=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_abs_top10_Co_Exp_Ess_across_expression.rds")
dim(copy_number)
essentiality=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Crispr_across_cell_Line_normalized.rds")
co_exp_ess=co_exp_ess[,1:11]
co_exp_ess$copy_number=copy_number[,4]
co_exp_ess$essentiality=as.vector(essentiality)
library(gbm)

setwd("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/GBR_regression_model_for_each_gene")
GBR_model=readRDS("top9_Abs_copy_comp_GBR_model.rds")
names(GBR_model)=as.vector(unique(co_exp_ess[,2]))
#train_model_pre<-NULL
train_model_pre<-NULL
train_model_pre_cor<<-NULL
one_gene_model<-function(gene){
  index=which(co_exp_ess[,2] == gene)
  data=co_exp_ess[index[1:385],3:13]
  model_index=match(gene,names(GBR_model))

  y_pre=predict(GBR_model[[model_index]],data)
  train_model_pre<<-cbind(train_model_pre,y_pre)
  train_model_pre_cor<<-rbind(train_model_pre_cor,c(gene,unlist(cor.test(y_pre,co_exp_ess[index[1:385],13]))[c(3,4)]))
  
  }
result=apply(matrix(as.vector(unique(co_exp_ess[,2]))),1,one_gene_model)

saveRDS(train_model_pre,file="top9_Abs_copy_comp_GBR_model_train_predict.rds")
saveRDS(train_model_pre_cor,file="top9_Abs_copy_comp_GBR_model_train_predict_cor.rds")
```



```{r}
copy_number=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_itsel_across_expression_copy_mut.rds")
co_exp_ess=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_abs_top10_Co_Exp_Ess_across_expression.rds")
dim(copy_number)
essentiality=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Crispr_across_cell_Line_normalized.rds")
co_exp_ess=co_exp_ess[,1:11]
co_exp_ess$copy_number=copy_number[,4]
co_exp_ess$essentiality=as.vector(essentiality)
library(xgboost)
library(stringr)

setwd("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/Six_kinds_of_baseline_model_for_one_gene_one_model/Co_exp_ess_Abs_9_cor_add_CNV_XGBoost")
xgboost_model=readRDS("top9_Abs_copy_linear_model.rds")
names(xgboost_model)=as.vector(unique(co_exp_ess[,2]))
#train_model_pre<-NULL
train_model_pre<-NULL
train_model_pre_cor<<-NULL
one_gene_model<-function(gene){
  index=which(co_exp_ess[,2] == gene)
  data=xgb.DMatrix(data=as.matrix(co_exp_ess[index[1:385],3:12]))
  
  model_index=match(gene,names(xgboost_model))
  y_pre=predict(xgboost_model[[model_index]],data)
  train_model_pre<<-cbind(train_model_pre,y_pre)
  train_model_pre_cor<<-rbind(train_model_pre_cor,c(gene,unlist(cor.test(y_pre,co_exp_ess[index[1:385],13]))[c(3,4)]))
  
  }
result=apply(matrix(as.vector(unique(co_exp_ess[,2]))),1,one_gene_model)

saveRDS(train_model_pre,file="top9_Abs_copy_comp_xgboost_model_train_predict.rds")
saveRDS(train_model_pre_cor,file="top9_Abs_copy_comp_xgboost_model_train_predict_cor.rds")
```



```{r}
copy_number=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_itsel_across_expression_copy_mut.rds")
co_exp_ess=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Gene_abs_top10_Co_Exp_Ess_across_expression.rds")
dim(copy_number)
essentiality=readRDS("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_collect/Feature_collect_result/Crispr_across_cell_Line_normalized.rds")
co_exp_ess=co_exp_ess[,1:11]
co_exp_ess$copy_number=copy_number[,4]
co_exp_ess$essentiality=as.vector(essentiality)
library(e1071)

setwd("/mnt/Storage/home/hanya/project/Predict_essentiality_based_expression/Feature_selection_linear_model/Co_exp_ess_SVM")
svm_model=readRDS("abs_SVM_model_add_CNV.rds")
names(svm_model)=as.vector(unique(co_exp_ess[,2]))
#train_model_pre<-NULL
train_model_pre<-NULL
train_model_pre_cor<<-NULL
one_gene_model<-function(gene){
  index=which(co_exp_ess[,2] == gene)
  data=as.matrix(co_exp_ess[index[1:385],3:12])
  if(length(which(is.na(data)))>0){
    data=as.matrix(data)
    data[which(is.na(data))]=0
    data=as.data.frame(data)}
  
  model_index=match(gene,names(svm_model))
  y_pre=predict(svm_model[[model_index]],data)
  train_model_pre<<-cbind(train_model_pre,y_pre)
  train_model_pre_cor<<-rbind(train_model_pre_cor,c(gene,unlist(cor.test(y_pre,co_exp_ess[index[1:385],13]))[c(3,4)]))
  }
result=apply(matrix(as.vector(unique(co_exp_ess[,2]))[16300:16371]),1,one_gene_model)

saveRDS(train_model_pre,file="top9_Abs_copy_comp_svm_model_train_predict.rds")
saveRDS(train_model_pre_cor,file="top9_Abs_copy_comp_svm_model_train_predict_cor.rds")

dim(train_model_pre_cor)
dim(train_model_pre)
train_model_pre=readRDS("top9_Abs_copy_comp_svm_model_train_predict.rds")
train_model_pre_cor=readRDS("top9_Abs_copy_comp_svm_model_train_predict_cor.rds")
```



```{r}
essentiality=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_collect/Crispr_across_cell_Line_normalized.rds")
GBR_predict=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/GBR_regression_model_for_each_gene/top9_Abs_copy_comp_GBR_model_train_predict.rds")
dim(GBR_predict)
dim(essentiality)

cor_sample=apply(matrix(1:385),1,function(x) unlist(cor.test(as.numeric(as.vector(unlist(essentiality[x,]))),as.numeric(as.vector(unlist(GBR_predict[x,])))))[c(3,4)])
cor_sample=data.frame(t(cor_sample))
cor_sample$estimate.cor=as.numeric(as.vector(unlist(cor_sample$estimate.cor)))
mean(cor_sample$estimate.cor)#0.26
rownames(cor_sample)=rownames(essentiality)[1:385]
colnames(cor_sample)=c("P_value","Pearson_Correlation")
saveRDS(cor_sample,"/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/GBR_regression_model_for_each_gene/top9_Abs_copy_comp_GBR_model_train_sample_cor.rds")


#LR
LR_predict=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/LR_linear_regression_for_each_gene/top9_Abs_copy_comp_LR_model_train_predict.rds")
dim(LR_predict)
dim(essentiality)

cor_sample=apply(matrix(1:385),1,function(x) unlist(cor.test(as.numeric(as.vector(unlist(essentiality[x,]))),as.numeric(as.vector(unlist(LR_predict[x,])))))[c(3,4)])
cor_sample=data.frame(t(cor_sample))
cor_sample$estimate.cor=as.numeric(as.vector(unlist(cor_sample$estimate.cor)))
mean(cor_sample$estimate.cor)#0.26
rownames(cor_sample)=rownames(essentiality)[1:385]
colnames(cor_sample)=c("P_value","Pearson_Correlation")
saveRDS(cor_sample,"/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/LR_linear_regression_for_each_gene/top9_Abs_copy_comp_LR_model_train_sample_cor.rds")


#Ridge_regression
Ridge_predict=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Ridge_regression_for_each_gene/top9_Abs_copy_comp_Ridge_model_train_predict.rds")
dim(Ridge_predict)
dim(essentiality)

cor_sample=apply(matrix(1:385),1,function(x) unlist(cor.test(as.numeric(as.vector(unlist(essentiality[x,]))),as.numeric(as.vector(unlist(Ridge_predict[x,])))))[c(3,4)])
cor_sample=data.frame(t(cor_sample))
cor_sample$estimate.cor=as.numeric(as.vector(unlist(cor_sample$estimate.cor)))
mean(cor_sample$estimate.cor)#0.26
rownames(cor_sample)=rownames(essentiality)[1:385]
colnames(cor_sample)=c("P_value","Pearson_Correlation")
saveRDS(cor_sample,"/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Ridge_regression_for_each_gene/top9_Abs_copy_comp_Ridge_model_train_sample_cor.rds")


#xgboost
xgboost_predict=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Co_exp_ess_Linear_regression/Co_exp_ess_top9_copy_number_linear/top9_Abs_copy_comp_xgboost_model_train_predict.rds")
dim(xgboost_predict)
dim(essentiality)

cor_sample=apply(matrix(1:385),1,function(x) unlist(cor.test(as.numeric(as.vector(unlist(essentiality[x,]))),as.numeric(as.vector(unlist(xgboost_predict[x,])))))[c(3,4)])
cor_sample=data.frame(t(cor_sample))
cor_sample$estimate.cor=as.numeric(as.vector(unlist(cor_sample$estimate.cor)))
mean(cor_sample$estimate.cor)#0.26
rownames(cor_sample)=rownames(essentiality)[1:385]
colnames(cor_sample)=c("P_value","Pearson_Correlation")
saveRDS(cor_sample,"/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Co_exp_ess_Linear_regression/Co_exp_ess_top9_copy_number_linear/top9_Abs_copy_comp_xgboost_model_train_sample_cor.rds")


#SVM model
svm_predict=readRDS("/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Co_exp_ess_SVM/top9_Abs_copy_comp_svm_model_train_predict.rds")
dim(svm_predict)
dim(essentiality)

cor_sample=apply(matrix(1:385),1,function(x) unlist(cor.test(as.numeric(as.vector(unlist(essentiality[x,]))),as.numeric(as.vector(unlist(svm_predict[x,])))))[c(3,4)])
cor_sample=data.frame(t(cor_sample))
cor_sample$estimate.cor=as.numeric(as.vector(unlist(cor_sample$estimate.cor)))
mean(cor_sample$estimate.cor)#0.26
rownames(cor_sample)=rownames(essentiality)[1:385]
colnames(cor_sample)=c("P_value","Pearson_Correlation")
saveRDS(cor_sample,"/Users/yahan/Desktop/Predict_essential_score/Feature_selection_linear_model/Co_exp_ess_SVM/top9_Abs_copy_comp_svm_model_train_sample_cor.rds")
```



```{r}
#subset the co

```

