---
title: "Untitled"
output: html_document
---

```{r}
setwd("/data/home/hanya/predict_essential/Sanger_data_Valid/")
gene_list=as.vector(unlist(read.table("gene_identifiers_latest.csv",header=F,sep=",",fill=T,quote="")[-1,1]))
sample_list=as.vector(unlist(read.table("model_list_latest.csv",header=F,sep=",",fill=T,quote="")[-1,1]))
read_count=read.table("rnaseq_latest.csv",sep=",",header=T,quote = "")

get_raw_count_mat<-function(x){
  sample_index=which(read_count[,2]==x)
  temp=read_count[sample_index,c(1,3)]
  gene_index=match(gene_list,temp[,1])
  temp1=rep(0,42475)
  temp1=temp[gene_index,2]
  return(temp1)
}
result=apply(matrix(sample_list),1,get_raw_count_mat)
dim(result)
result=t(result)
gene_ensg=as.vector(unlist(read.table("gene_identifiers_latest.csv",header=F,sep=",",fill=T,quote="")[-1,3]))
colnames(result)=gene_ensg
rownames(result)=sample_list
saveRDS(result,file="Sanger_read_count.rds")

setwd("/data/home/hanya/predict_essential/Sanger_data_Valid/")
result=readRDS("Sanger_read_count.rds")
getTPM <- function(countMat, idType = "Ensembl"){
  ensembl = read.csv("ensembl_hg38_reference.txt",
                     check.names = FALSE)
  ensembl$Length <- abs(ensembl$`Gene end (bp)` - ensembl$`Gene start (bp)`)
  if(toupper(idType) == "ENSEMBL"){
    len <- ensembl[match(rownames(countMat),ensembl$`Gene stable ID`), "Length"]
  }
  else if(toupper(idType) == "SYMBOL")
    len <- ensembl[match(rownames(countMat),ensembl$`Gene name`), "Length"]
  else
    stop("Please input right type of gene name, such as Ensembl or gene Symbol ...")

  na_idx = which(is.na(len))
  if(length(na_idx)>0){
    warning(paste0("Omit ", length(na_idx), " genes of which length is not available !"))
    countMat = countMat[!is.na(len),]
    len = len[!is.na(len)]
  }
  tmp <- countMat / len
  TPM <- 1e6 * t(t(tmp) / colSums(tmp))
  TPM = TPM[!duplicated(rownames(TPM)),]
  return(TPM)
}
result[which(is.na(result))]=0
result1=getTPM(t(result))#每一行是一个基因
result1=t(result1)#得到的结果中基因名是symbol.用ensembl的文件转成ENSG,再用gene_list中的转成基因ID. 
gene_list=read.table("gene_identifiers_latest.csv",header=F,sep=",",fill=T,quote="")

index=match(colnames(result1),gene_list[,3])
colnames(result1)=as.vector(unlist(gene_list[index,4]))
colnames(result1)=unlist(lapply(strsplit(colnames(result1),"\\."),function(x) x[1]))
saveRDS(result1,file="Sanger_RNASeq_TPM.rds")
```







```{r}
setwd("/Users/yahan/Desktop/predicted_gene_essential/Sanger_institute_data_Valid/")
tpm_matrix=readRDS("Sanger_RNASeq_TPM.rds")
gene_order=as.vector(unlist(read.table("DepMap_gene_expression_gene_order.txt")))
cell_line_with_crispr=read.table("02b_MageckFDRs.tsv",sep="\t",header=F)
cell_line_des=read.table("model_list_latest.csv",header=F,sep=",",fill=T,quote="")


index=match(as.vector(unlist(cell_line_with_crispr[1,])),as.character(as.vector(unlist(cell_line_des[,2]))))
cell_line=cell_line_des[index[-1],1]
index=match(cell_line,rownames(tpm_matrix))
tpm_matrix=tpm_matrix[index,]

#这里有居然有276个基因是没有表达的。
index=match(gene_order,colnames(tpm_matrix))
length(which(is.na(index)))
#same gene with two transcription ,random select one.
#SCALE : for each column do normalization.
#其中有3个基因的表达值没有找到。我们用0来代替。
#这三个基因83935 283777 267004，所以我们可以先事先设置好为0.
temp=matrix(rep(0,3*325),ncol=3)
colnames(temp)=c("83935","283777","267004")
tpm_matrix=cbind(tpm_matrix,temp)
index=match(gene_order,colnames(tpm_matrix))
length(which(is.na(index)))
tpm_matrix=tpm_matrix[,index]
length(which(is.na(tpm_matrix)))
length(which(is.nan(tpm_matrix)))
tpm_matrix[which(is.na(tpm_matrix))]=0
tpm_matrix[which(is.nan(tpm_matrix))]=0
saveRDS(tpm_matrix,file="Sanger_RNASeq_TPM_used_test_performance.rds")

#列是基因，across cell line
tpm_matrix1=scale(tpm_matrix,center = T,scale = T)
tpm_matrix1[which(is.na(tpm_matrix1))]=0
tpm_matrix1[which(is.nan(tpm_matrix1))]=0
write.table(tpm_matrix1,file="Sanger_RNASeq_TPM_across_cell_Nor.txt",col.names = F,row.names = F,sep="\t",quote = F)
#在进行Z-score的时候如果分母为0就会出现NA的情况
tpm_matrix2=t(scale(t(tpm_matrix),center = T,scale = T))
tpm_matrix2[which(is.na(tpm_matrix2))]=0
tpm_matrix2[which(is.nan(tpm_matrix2))]=0
write.table(tpm_matrix2,file="Sanger_RNASeq_TPM_within_cell_Nor.txt",col.names = F,row.names = F,sep="\t",quote = F)
```





